#############################################################################
# Makefile for building: build/debug/Tkacz.app/Contents/MacOS/Tkacz
# Generated by qmake (3.0) (Qt 5.2.0)
# Project:  Tkacz.pro
# Template: app
# Command: /Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/bin/qmake -o Makefile Tkacz.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/macx-clang -I. -I/usr/local/include -I/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/lib/QtGui.framework/Versions/5/Headers -I/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/lib/QtCore.framework/Versions/5/Headers -Ibuild/debug/moc -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AGL.framework/Headers -Ibuild/debug/ui -F/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/lib
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -stdlib=libc++ -mmacosx-version-min=10.7
LIBS          = $(SUBLIBS) -F/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework Foundation -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/debug/obj/

####### Files

SOURCES       = core/tkacz.cpp \
		gui/main.cpp \
		core/data/primitives.cpp \
		core/data/taxonomies.cpp \
		core/data/types.cpp \
		core/schema/loader.cpp build/debug/qrc/qrc_common.cpp \
		build/debug/qrc/qrc_icons.cpp
OBJECTS       = build/debug/obj/tkacz.o \
		build/debug/obj/main.o \
		build/debug/obj/primitives.o \
		build/debug/obj/taxonomies.o \
		build/debug/obj/types.o \
		build/debug/obj/loader.o \
		build/debug/obj/qrc_common.o \
		build/debug/obj/qrc_icons.o
DIST          = /Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/spec_pre.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/qdevice.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/device_config.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/common/shell-unix.conf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/common/unix.conf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/common/mac.conf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/common/macx.conf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/common/gcc-base.conf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/common/clang.conf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/common/clang-mac.conf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/qconfig.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_clucene.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_designercomponents.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_platformsupport.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_quickparticles.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/qt_functions.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/qt_config.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/spec_post.prf \
		.qmake.cache \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/default_pre.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/unix/default_pre.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/mac/default_pre.prf \
		Tkacz.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/resolve_config.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/default_post.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/c++11.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/qt.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/resources.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/moc.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/uic.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/unix/thread.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/warn_on.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/mac/rez.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/exceptions.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/yacc.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/lex.prf \
		Tkacz.pro \
		resources/qrc/common.qrc \
		resources/qrc/icons.qrc \
		Tkacz.pro
QMAKE_TARGET  = Tkacz
DESTDIR       = build/debug/#avoid trailing-slash linebreak
TARGET        = build/debug/Tkacz.app/Contents/MacOS/Tkacz

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk \
		-std=c++11 \
		-stdlib=libc++ \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile build/debug/Tkacz.app/Contents/PkgInfo build/debug/Tkacz.app/Contents/Resources/empty.lproj build/debug/Tkacz.app/Contents/Info.plist build/debug/Tkacz.app/Contents/Resources/app.icns $(TARGET)

$(TARGET): build/debug/ui/ui_dlgAbout.h build/debug/ui/ui_dlgCollectionEditor.h build/debug/ui/ui_dlgCrashReporter.h build/debug/ui/ui_dlgFirstStart.h build/debug/ui/ui_dlgPreferences.h build/debug/ui/ui_mainWindow.h build/debug/ui/ui_mwListOfEntryPoints.h build/debug/ui/ui_mwLocationBar.h build/debug/ui/ui_mwMainView.h build/debug/ui/ui_mwPageEditor.h build/debug/ui/ui_mwPagePropertiesEditor.h build/debug/ui/ui_mwPagesList.h build/debug/ui/ui_mwPageView.h build/debug/ui/ui_mwRepositorySettingsView.h build/debug/ui/ui_mwToolBarWidget.h build/debug/ui/ui_propertyEditWidget.h $(OBJECTS)  
	@test -d build/debug/Tkacz.app/Contents/MacOS/ || mkdir -p build/debug/Tkacz.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Tkacz.pro .qmake.cache /Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/macx-clang/qmake.conf /Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/spec_pre.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/qdevice.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/device_config.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/common/shell-unix.conf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/common/unix.conf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/common/mac.conf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/common/macx.conf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/common/gcc-base.conf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/common/clang.conf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/common/clang-mac.conf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/qconfig.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_clucene.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_designercomponents.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_platformsupport.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_quickparticles.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/qt_functions.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/qt_config.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/spec_post.prf \
		.qmake.cache \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/default_pre.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/unix/default_pre.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/mac/default_pre.prf \
		Tkacz.pri \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/resolve_config.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/default_post.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/c++11.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/qt.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/resources.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/moc.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/uic.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/unix/thread.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/warn_on.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/mac/rez.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/exceptions.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/yacc.prf \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/lex.prf \
		Tkacz.pro \
		resources/qrc/common.qrc \
		resources/qrc/icons.qrc \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile Tkacz.pro
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/spec_pre.prf:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/qdevice.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/device_config.prf:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/common/shell-unix.conf:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/common/unix.conf:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/common/mac.conf:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/common/macx.conf:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/common/gcc-base.conf:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/common/gcc-base-mac.conf:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/common/clang.conf:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/common/clang-mac.conf:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/qconfig.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_clucene.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_core.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_declarative.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_designercomponents.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_help.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_network.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_platformsupport.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_quickparticles.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_script.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_webkit.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/qt_functions.prf:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/qt_config.prf:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/macx-clang/qmake.conf:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/spec_post.prf:
.qmake.cache:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/exclusive_builds.prf:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/default_pre.prf:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/unix/default_pre.prf:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/mac/default_pre.prf:
Tkacz.pri:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/resolve_config.prf:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/default_post.prf:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/c++11.prf:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/mac/sdk.prf:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/mac/default_post.prf:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/mac/objective_c.prf:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/qt.prf:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/resources.prf:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/moc.prf:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/unix/opengl.prf:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/uic.prf:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/unix/thread.prf:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/warn_on.prf:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/mac/rez.prf:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/testcase_targets.prf:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/exceptions.prf:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/yacc.prf:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/features/lex.prf:
Tkacz.pro:
resources/qrc/common.qrc:
resources/qrc/icons.qrc:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Tkacz.pro

qmake_all: FORCE

build/debug/Tkacz.app/Contents/PkgInfo: 
	@test -d build/debug/Tkacz.app/Contents || mkdir -p build/debug/Tkacz.app/Contents
	@$(DEL_FILE) build/debug/Tkacz.app/Contents/PkgInfo
	@echo "APPL????" >build/debug/Tkacz.app/Contents/PkgInfo
build/debug/Tkacz.app/Contents/Resources/empty.lproj: 
	@test -d build/debug/Tkacz.app/Contents/Resources || mkdir -p build/debug/Tkacz.app/Contents/Resources
	@touch build/debug/Tkacz.app/Contents/Resources/empty.lproj
	
build/debug/Tkacz.app/Contents/Info.plist: 
	@test -d build/debug/Tkacz.app/Contents || mkdir -p build/debug/Tkacz.app/Contents
	@$(DEL_FILE) build/debug/Tkacz.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,app.icns,g" -e "s,@EXECUTABLE@,Tkacz,g" -e "s,@TYPEINFO@,????,g" /Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/mkspecs/macx-clang/Info.plist.app >build/debug/Tkacz.app/Contents/Info.plist
build/debug/Tkacz.app/Contents/Resources/app.icns: platform/osx/app.icns
	@test -d build/debug/Tkacz.app/Contents/Resources/ || mkdir -p build/debug/Tkacz.app/Contents/Resources/
	@$(DEL_FILE) build/debug/Tkacz.app/Contents/Resources/app.icns
	@$(COPY_FILE) platform/osx/app.icns build/debug/Tkacz.app/Contents/Resources/app.icns
dist: 
	@test -d build/debug/obj/Tkacz1.0.0 || mkdir -p build/debug/obj/Tkacz1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/debug/obj/Tkacz1.0.0/ && $(COPY_FILE) --parents resources/qrc/common.qrc resources/qrc/icons.qrc build/debug/obj/Tkacz1.0.0/ && $(COPY_FILE) --parents core/tkacz.h core/data/primitives.h core/data/taxonomies.h core/data/types.h core/io/DataBridge.h core/schema/loader.h build/debug/obj/Tkacz1.0.0/ && $(COPY_FILE) --parents core/tkacz.cpp gui/main.cpp core/data/primitives.cpp core/data/taxonomies.cpp core/data/types.cpp core/schema/loader.cpp build/debug/obj/Tkacz1.0.0/ && $(COPY_FILE) --parents resources/ui/dlgAbout.ui resources/ui/dlgCollectionEditor.ui resources/ui/dlgCrashReporter.ui resources/ui/dlgFirstStart.ui resources/ui/dlgPreferences.ui resources/ui/mainWindow.ui resources/ui/mwListOfEntryPoints.ui resources/ui/mwLocationBar.ui resources/ui/mwMainView.ui resources/ui/mwPageEditor.ui resources/ui/mwPagePropertiesEditor.ui resources/ui/mwPagesList.ui resources/ui/mwPageView.ui resources/ui/mwRepositorySettingsView.ui resources/ui/mwToolBarWidget.ui resources/ui/propertyEditWidget.ui build/debug/obj/Tkacz1.0.0/ && (cd `dirname build/debug/obj/Tkacz1.0.0` && $(TAR) Tkacz1.0.0.tar Tkacz1.0.0 && $(COMPRESS) Tkacz1.0.0.tar) && $(MOVE) `dirname build/debug/obj/Tkacz1.0.0`/Tkacz1.0.0.tar.gz . && $(DEL_FILE) -r build/debug/obj/Tkacz1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r build/debug/Tkacz.app
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all: build/debug/qrc/qrc_common.cpp build/debug/qrc/qrc_icons.cpp
compiler_rcc_clean:
	-$(DEL_FILE) build/debug/qrc/qrc_common.cpp build/debug/qrc/qrc_icons.cpp
build/debug/qrc/qrc_common.cpp: resources/qrc/common.qrc \
		resources/qrc/common/i18n/tkacz_fr.qm \
		resources/qrc/common/actions/menus.xml \
		resources/qrc/common/actions/actions.xml \
		resources/qrc/common/tkacz/acknowledgements.html \
		resources/qrc/common/tkacz/license.html
	/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/bin/rcc -name common resources/qrc/common.qrc -o build/debug/qrc/qrc_common.cpp

build/debug/qrc/qrc_icons.cpp: resources/qrc/icons.qrc \
		resources/qrc/icons/actions/searchFind.svg \
		resources/qrc/icons/actions/repositoryConfigure-off.svg \
		resources/qrc/icons/actions/viewCollections-on.svg \
		resources/qrc/icons/actions/_previous.svg \
		resources/qrc/icons/actions/formatCharacterEmphasis.svg \
		resources/qrc/icons/actions/viewCollections-off.svg \
		resources/qrc/icons/actions/repositoryConfigure-on.svg \
		resources/qrc/icons/actions/windowFullscreen.svg \
		resources/qrc/icons/actions/_next.svg \
		resources/qrc/icons/actions/collectionCreateFromRules-off.svg \
		resources/qrc/icons/actions/formatCharacterStrongEmphasis.svg \
		resources/qrc/icons/actions/pageCreatePopup.svg \
		resources/qrc/icons/actions/collectionCreateFromRules-on.svg \
		resources/qrc/icons/types/box.svg \
		resources/qrc/icons/types/person.svg \
		resources/qrc/icons/types/book.svg \
		resources/qrc/icons/collections/collection-dynamic.svg \
		resources/qrc/icons/collections/collection-static.svg \
		resources/qrc/icons/collections/persons.svg \
		resources/qrc/icons/collections/books.svg
	/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/bin/rcc -name icons resources/qrc/icons.qrc -o build/debug/qrc/qrc_icons.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: build/debug/ui/ui_dlgAbout.h build/debug/ui/ui_dlgCollectionEditor.h build/debug/ui/ui_dlgCrashReporter.h build/debug/ui/ui_dlgFirstStart.h build/debug/ui/ui_dlgPreferences.h build/debug/ui/ui_mainWindow.h build/debug/ui/ui_mwListOfEntryPoints.h build/debug/ui/ui_mwLocationBar.h build/debug/ui/ui_mwMainView.h build/debug/ui/ui_mwPageEditor.h build/debug/ui/ui_mwPagePropertiesEditor.h build/debug/ui/ui_mwPagesList.h build/debug/ui/ui_mwPageView.h build/debug/ui/ui_mwRepositorySettingsView.h build/debug/ui/ui_mwToolBarWidget.h build/debug/ui/ui_propertyEditWidget.h
compiler_uic_clean:
	-$(DEL_FILE) build/debug/ui/ui_dlgAbout.h build/debug/ui/ui_dlgCollectionEditor.h build/debug/ui/ui_dlgCrashReporter.h build/debug/ui/ui_dlgFirstStart.h build/debug/ui/ui_dlgPreferences.h build/debug/ui/ui_mainWindow.h build/debug/ui/ui_mwListOfEntryPoints.h build/debug/ui/ui_mwLocationBar.h build/debug/ui/ui_mwMainView.h build/debug/ui/ui_mwPageEditor.h build/debug/ui/ui_mwPagePropertiesEditor.h build/debug/ui/ui_mwPagesList.h build/debug/ui/ui_mwPageView.h build/debug/ui/ui_mwRepositorySettingsView.h build/debug/ui/ui_mwToolBarWidget.h build/debug/ui/ui_propertyEditWidget.h
build/debug/ui/ui_dlgAbout.h: resources/ui/dlgAbout.ui
	/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/bin/uic resources/ui/dlgAbout.ui -o build/debug/ui/ui_dlgAbout.h

build/debug/ui/ui_dlgCollectionEditor.h: resources/ui/dlgCollectionEditor.ui
	/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/bin/uic resources/ui/dlgCollectionEditor.ui -o build/debug/ui/ui_dlgCollectionEditor.h

build/debug/ui/ui_dlgCrashReporter.h: resources/ui/dlgCrashReporter.ui
	/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/bin/uic resources/ui/dlgCrashReporter.ui -o build/debug/ui/ui_dlgCrashReporter.h

build/debug/ui/ui_dlgFirstStart.h: resources/ui/dlgFirstStart.ui
	/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/bin/uic resources/ui/dlgFirstStart.ui -o build/debug/ui/ui_dlgFirstStart.h

build/debug/ui/ui_dlgPreferences.h: resources/ui/dlgPreferences.ui
	/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/bin/uic resources/ui/dlgPreferences.ui -o build/debug/ui/ui_dlgPreferences.h

build/debug/ui/ui_mainWindow.h: resources/ui/mainWindow.ui
	/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/bin/uic resources/ui/mainWindow.ui -o build/debug/ui/ui_mainWindow.h

build/debug/ui/ui_mwListOfEntryPoints.h: resources/ui/mwListOfEntryPoints.ui
	/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/bin/uic resources/ui/mwListOfEntryPoints.ui -o build/debug/ui/ui_mwListOfEntryPoints.h

build/debug/ui/ui_mwLocationBar.h: resources/ui/mwLocationBar.ui
	/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/bin/uic resources/ui/mwLocationBar.ui -o build/debug/ui/ui_mwLocationBar.h

build/debug/ui/ui_mwMainView.h: resources/ui/mwMainView.ui
	/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/bin/uic resources/ui/mwMainView.ui -o build/debug/ui/ui_mwMainView.h

build/debug/ui/ui_mwPageEditor.h: resources/ui/mwPageEditor.ui
	/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/bin/uic resources/ui/mwPageEditor.ui -o build/debug/ui/ui_mwPageEditor.h

build/debug/ui/ui_mwPagePropertiesEditor.h: resources/ui/mwPagePropertiesEditor.ui
	/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/bin/uic resources/ui/mwPagePropertiesEditor.ui -o build/debug/ui/ui_mwPagePropertiesEditor.h

build/debug/ui/ui_mwPagesList.h: resources/ui/mwPagesList.ui
	/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/bin/uic resources/ui/mwPagesList.ui -o build/debug/ui/ui_mwPagesList.h

build/debug/ui/ui_mwPageView.h: resources/ui/mwPageView.ui
	/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/bin/uic resources/ui/mwPageView.ui -o build/debug/ui/ui_mwPageView.h

build/debug/ui/ui_mwRepositorySettingsView.h: resources/ui/mwRepositorySettingsView.ui
	/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/bin/uic resources/ui/mwRepositorySettingsView.ui -o build/debug/ui/ui_mwRepositorySettingsView.h

build/debug/ui/ui_mwToolBarWidget.h: resources/ui/mwToolBarWidget.ui
	/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/bin/uic resources/ui/mwToolBarWidget.ui -o build/debug/ui/ui_mwToolBarWidget.h

build/debug/ui/ui_propertyEditWidget.h: resources/ui/propertyEditWidget.ui
	/Users/thblt/Documents/Coderies/Qt5.2.0/5.2.0-beta1/clang_64/bin/uic resources/ui/propertyEditWidget.ui -o build/debug/ui/ui_propertyEditWidget.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_uic_clean 

####### Compile

build/debug/obj/tkacz.o: core/tkacz.cpp core/tkacz.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/obj/tkacz.o core/tkacz.cpp

build/debug/obj/main.o: gui/main.cpp build/debug/ui/ui_dlgCollectionEditor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/obj/main.o gui/main.cpp

build/debug/obj/primitives.o: core/data/primitives.cpp core/data/primitives.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/obj/primitives.o core/data/primitives.cpp

build/debug/obj/taxonomies.o: core/data/taxonomies.cpp core/data/taxonomies.h \
		core/data/types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/obj/taxonomies.o core/data/taxonomies.cpp

build/debug/obj/types.o: core/data/types.cpp core/data/types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/obj/types.o core/data/types.cpp

build/debug/obj/loader.o: core/schema/loader.cpp core/schema/loader.h \
		/usr/local/include/xercesc/util/PlatformUtils.hpp \
		/usr/local/include/xercesc/util/XercesDefs.hpp \
		/usr/local/include/xercesc/util/Xerces_autoconf_config.hpp \
		/usr/local/include/xercesc/util/XercesVersion.hpp \
		/usr/local/include/xercesc/util/XMLException.hpp \
		/usr/local/include/xercesc/util/XMemory.hpp \
		/usr/local/include/xercesc/util/XMLExceptMsgs.hpp \
		/usr/local/include/xercesc/dom/DOMError.hpp \
		/usr/local/include/xercesc/util/XMLUni.hpp \
		/usr/local/include/xercesc/framework/XMLErrorReporter.hpp \
		/usr/local/include/xercesc/util/PanicHandler.hpp \
		/usr/local/include/xercesc/util/XMLFileMgr.hpp \
		/usr/local/include/xercesc/util/XMLMutexMgr.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/obj/loader.o core/schema/loader.cpp

build/debug/obj/qrc_common.o: build/debug/qrc/qrc_common.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/obj/qrc_common.o build/debug/qrc/qrc_common.cpp

build/debug/obj/qrc_icons.o: build/debug/qrc/qrc_icons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/obj/qrc_icons.o build/debug/qrc/qrc_icons.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

