"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup


py2appOptions = {
	'iconfile':'images/tkacz.icns',
    'plist': {'CFBundleShortVersionString':'0.1.0',
			'CFBundleIdentifier':"net.thblt.tkacz",
			'NSHumanReadableCopyright': 'Copyright © 2012-2013 Thibault Polge and contributors.'},
    'includes': {"sip", "sqlalchemy.dialects.sqlite"}
	}

setup(
	name="Tkacz",
	version = "0.0.1",
    app=['src/Tkacz.py'],
    #data_files=['*.mo'],
    options={'py2app': py2appOptions},
    install_requires=['PyQtStructuredTextEditor==0.1', 'PyYAML==3.10', 'Thblt-Pytools==0.1', 'SQLAlchemy==0.8.0'],
    setup_requires=['py2app'],
    include_package_data=True,
    
)
